---
- name: Setup nomad on nodes (without gossip configuration)
  hosts: all
  vars_files:
    - vars.yml  

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
      become: yes
  
    - name: Update apt and install unzip
      apt: update_cache=yes name=unzip state=latest
      become: yes
      
    - name: Download nomad archive
      become: false
      unarchive:
        src: "{{ nomad_zip_url }}"
        dest: /usr/local/bin/
        mode: 0700
        remote_src: yes

    - name: Create a data directory for Nomad
      file:
        path: /opt/nomad
        state: directory

    - name: Create systemd service file
      template:
        src: template_nomad.service
        dest: /etc/systemd/system/nomad.service

    - name: Create nomad config file directory
      file: path=/etc/nomad.d state=directory mode=0755

    - name: Create nomad config file
      template:
        src: template_nomad.hcl
        dest: /etc/nomad.d/nomad.hcl

    - name: Start service
      systemd:
        name: nomad
        state: started
